/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACE;

/**
 *
 * @author Jonas
 */
public class BlocoNotas extends javax.swing.JFrame {

    /**
     * Creates new form BlocoNotas
     */
    public BlocoNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator5 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArquivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mAbrir = new javax.swing.JMenuItem();
        mSalvar = new javax.swing.JMenuItem();
        mSalvarComo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mConfigurarP = new javax.swing.JMenuItem();
        mImprimir = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mSair = new javax.swing.JMenuItem();
        mEditar = new javax.swing.JMenu();
        mDesfazer = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mRecortar = new javax.swing.JMenuItem();
        mCopiar = new javax.swing.JMenuItem();
        mColar = new javax.swing.JMenuItem();
        mExcluir = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mLocalizar = new javax.swing.JMenuItem();
        mLocalizarP = new javax.swing.JMenuItem();
        mSubstituir = new javax.swing.JMenuItem();
        mIrPara = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mSelecionaTudo = new javax.swing.JMenuItem();
        mHrDt = new javax.swing.JMenuItem();
        mFormatar = new javax.swing.JMenu();
        mQuebra = new javax.swing.JMenuItem();
        mFonte = new javax.swing.JMenuItem();
        mExibir = new javax.swing.JMenu();
        mBarraStatus = new javax.swing.JMenuItem();
        mAjuda = new javax.swing.JMenu();
        mExibirAjuda = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mArquivo.setMnemonic('a');
        mArquivo.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Novo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mArquivo.add(jMenuItem1);

        mAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mAbrir.setText("Abrir");
        mArquivo.add(mAbrir);

        mSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mSalvar.setText("Salvar");
        mArquivo.add(mSalvar);

        mSalvarComo.setText("Salvar como...");
        mArquivo.add(mSalvarComo);
        mArquivo.add(jSeparator1);

        mConfigurarP.setText("Configurar Página...");
        mArquivo.add(mConfigurarP);

        mImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mImprimir.setText("Imprimir...");
        mArquivo.add(mImprimir);
        mArquivo.add(jSeparator2);

        mSair.setText("Sair");
        mArquivo.add(mSair);

        jMenuBar1.add(mArquivo);

        mEditar.setMnemonic('e');
        mEditar.setText("Editar");

        mDesfazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        mDesfazer.setText("Desfazer");
        mEditar.add(mDesfazer);
        mEditar.add(jSeparator3);

        mRecortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mRecortar.setText("Recortar");
        mEditar.add(mRecortar);

        mCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mCopiar.setText("Copiar");
        mEditar.add(mCopiar);

        mColar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        mColar.setText("Colar");
        mEditar.add(mColar);

        mExcluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        mExcluir.setText("Excluir");
        mEditar.add(mExcluir);
        mEditar.add(jSeparator4);

        mLocalizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mLocalizar.setText("Localizar");
        mEditar.add(mLocalizar);

        mLocalizarP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mLocalizarP.setText("Localizar Próxima");
        mEditar.add(mLocalizarP);

        mSubstituir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mSubstituir.setText("Substituir...");
        mEditar.add(mSubstituir);

        mIrPara.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mIrPara.setText("Ir para...");
        mEditar.add(mIrPara);
        mEditar.add(jSeparator6);

        mSelecionaTudo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mSelecionaTudo.setText("Selecionar tudo");
        mEditar.add(mSelecionaTudo);

        mHrDt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mHrDt.setText("Hora/Data");
        mEditar.add(mHrDt);

        jMenuBar1.add(mEditar);

        mFormatar.setMnemonic('f');
        mFormatar.setText("Formatar");

        mQuebra.setText("Quebra automática de linha");
        mFormatar.add(mQuebra);

        mFonte.setText("Fonte...");
        mFormatar.add(mFonte);

        jMenuBar1.add(mFormatar);

        mExibir.setMnemonic('x');
        mExibir.setText("Exibir");

        mBarraStatus.setText("Barra de status");
        mExibir.add(mBarraStatus);

        jMenuBar1.add(mExibir);

        mAjuda.setMnemonic('u');
        mAjuda.setText("Ajuda");

        mExibirAjuda.setText("Exibir Ajuda");
        mAjuda.add(mExibirAjuda);
        mAjuda.add(jSeparator7);

        mSobre.setText("Sobre o Bloco de Notas");
        mAjuda.add(mSobre);

        jMenuBar1.add(mAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlocoNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlocoNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlocoNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlocoNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlocoNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JMenuItem mAbrir;
    private javax.swing.JMenu mAjuda;
    private javax.swing.JMenu mArquivo;
    private javax.swing.JMenuItem mBarraStatus;
    private javax.swing.JMenuItem mColar;
    private javax.swing.JMenuItem mConfigurarP;
    private javax.swing.JMenuItem mCopiar;
    private javax.swing.JMenuItem mDesfazer;
    private javax.swing.JMenu mEditar;
    private javax.swing.JMenuItem mExcluir;
    private javax.swing.JMenu mExibir;
    private javax.swing.JMenuItem mExibirAjuda;
    private javax.swing.JMenuItem mFonte;
    private javax.swing.JMenu mFormatar;
    private javax.swing.JMenuItem mHrDt;
    private javax.swing.JMenuItem mImprimir;
    private javax.swing.JMenuItem mIrPara;
    private javax.swing.JMenuItem mLocalizar;
    private javax.swing.JMenuItem mLocalizarP;
    private javax.swing.JMenuItem mQuebra;
    private javax.swing.JMenuItem mRecortar;
    private javax.swing.JMenuItem mSair;
    private javax.swing.JMenuItem mSalvar;
    private javax.swing.JMenuItem mSalvarComo;
    private javax.swing.JMenuItem mSelecionaTudo;
    private javax.swing.JMenuItem mSobre;
    private javax.swing.JMenuItem mSubstituir;
    // End of variables declaration//GEN-END:variables
}
