/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACE;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author alunoces
 */
public class T_PRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form T_PRINCIPAL
     */
    public T_PRINCIPAL() {
        getContentPane().setBackground(Color.CYAN);
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenu = new javax.swing.JMenuBar();
        mncadastro = new javax.swing.JMenu();
        mnicliente = new javax.swing.JMenuItem();
        mniproduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnisair = new javax.swing.JMenuItem();
        mnpesquisa = new javax.swing.JMenu();
        mnCliente = new javax.swing.JMenu();
        pcliente = new javax.swing.JMenuItem();
        mnrelatorios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema XPTU");
        setResizable(false);

        mncadastro.setMnemonic('c');
        mncadastro.setText("Cadastro");

        mnicliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnicliente.setMnemonic('c');
        mnicliente.setText("Cliente");
        mnicliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniclienteActionPerformed(evt);
            }
        });
        mncadastro.add(mnicliente);

        mniproduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mniproduto.setMnemonic('p');
        mniproduto.setText("Produto");
        mniproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniprodutoActionPerformed(evt);
            }
        });
        mncadastro.add(mniproduto);
        mncadastro.add(jSeparator1);

        mnisair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mnisair.setMnemonic('s');
        mnisair.setText("Sair");
        mnisair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnisairActionPerformed(evt);
            }
        });
        mncadastro.add(mnisair);

        BarraMenu.add(mncadastro);

        mnpesquisa.setMnemonic('p');
        mnpesquisa.setText("Pesquisa");

        mnCliente.setText("Cliente");

        pcliente.setText("Cliente");
        mnCliente.add(pcliente);

        mnpesquisa.add(mnCliente);

        BarraMenu.add(mnpesquisa);

        mnrelatorios.setMnemonic('r');
        mnrelatorios.setText("Relatórios");
        BarraMenu.add(mnrelatorios);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniclienteActionPerformed
        new cliente(null,true).setVisible(true);   
    }//GEN-LAST:event_mniclienteActionPerformed

    private void mniprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniprodutoActionPerformed
        new produto(null,true).setVisible(true);
    }//GEN-LAST:event_mniprodutoActionPerformed

    private void mnisairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnisairActionPerformed
        // TODO add your handling code here:
        int status = JOptionPane.showConfirmDialog(null, "Deseja realmente sair da Aplicação", "Fechar Aplicação", JOptionPane.YES_NO_OPTION);
        if(status == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_mnisairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T_PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnCliente;
    private javax.swing.JMenu mncadastro;
    private javax.swing.JMenuItem mnicliente;
    private javax.swing.JMenuItem mniproduto;
    private javax.swing.JMenuItem mnisair;
    private javax.swing.JMenu mnpesquisa;
    private javax.swing.JMenu mnrelatorios;
    private javax.swing.JMenuItem pcliente;
    // End of variables declaration//GEN-END:variables
}
