/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACE;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class TPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form t_principal
     */
    public TPrincipal() {
        getContentPane().setBackground(Color.LIGHT_GRAY);//SET A COR DO BACKGROUND
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);//MAXIMIZA A TELA INICIAL
        //a propriedade RESIZABLE habilita ou desabilita o maximizar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenu = new javax.swing.JMenuBar();
        mncadastro = new javax.swing.JMenu();
        mnicliente = new javax.swing.JMenuItem();
        mniproduto = new javax.swing.JMenuItem();
        mnifornecedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnisair = new javax.swing.JMenuItem();
        mnpesquisa = new javax.swing.JMenu();
        mncliente = new javax.swing.JMenu();
        pcliente = new javax.swing.JMenuItem();
        mnrelatorios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA XPTO");
        setResizable(false);

        mncadastro.setMnemonic('C');
        mncadastro.setText("Cadastro");

        mnicliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnicliente.setMnemonic('c');
        mnicliente.setText("Cliente");
        mnicliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniclienteActionPerformed(evt);
            }
        });
        mncadastro.add(mnicliente);

        mniproduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mniproduto.setMnemonic('p');
        mniproduto.setText("Produto");
        mniproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniprodutoActionPerformed(evt);
            }
        });
        mncadastro.add(mniproduto);

        mnifornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        mnifornecedor.setMnemonic('f');
        mnifornecedor.setText("Fornecedor");
        mnifornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnifornecedorActionPerformed(evt);
            }
        });
        mncadastro.add(mnifornecedor);
        mncadastro.add(jSeparator1);

        mnisair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mnisair.setMnemonic('S');
        mnisair.setText("Sair");
        mnisair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnisairActionPerformed(evt);
            }
        });
        mncadastro.add(mnisair);

        BarraMenu.add(mncadastro);
        mncadastro.getAccessibleContext().setAccessibleName("File");

        mnpesquisa.setMnemonic('P');
        mnpesquisa.setText("Pesquisa");

        mncliente.setText("Cliente");

        pcliente.setText("Visualizar");
        pcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pclienteActionPerformed(evt);
            }
        });
        mncliente.add(pcliente);

        mnpesquisa.add(mncliente);

        BarraMenu.add(mnpesquisa);

        mnrelatorios.setMnemonic('R');
        mnrelatorios.setText("Relatórios");
        BarraMenu.add(mnrelatorios);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniclienteActionPerformed
        // TODO add your handling code here:
        new Cliente(null, true).setVisible(true);//abre a janela de cliente
    }//GEN-LAST:event_mniclienteActionPerformed

    private void pclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pclienteActionPerformed

    private void mniprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniprodutoActionPerformed
        // TODO add your handling code here:
        new Produto(null, true).setVisible(true);//abre a janela de produto
    }//GEN-LAST:event_mniprodutoActionPerformed

    private void mnisairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnisairActionPerformed
        // TODO add your handling code here:
        int status = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Fechar", JOptionPane.YES_NO_OPTION);
        if(status==JOptionPane.YES_OPTION){
           System.exit(0);//sai do sistema todo
        }
    }//GEN-LAST:event_mnisairActionPerformed

    private void mnifornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnifornecedorActionPerformed
        // TODO add your handling code here:
        new Fornecedor(null, true).setVisible(true);
    }//GEN-LAST:event_mnifornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mncadastro;
    private javax.swing.JMenu mncliente;
    private javax.swing.JMenuItem mnicliente;
    private javax.swing.JMenuItem mnifornecedor;
    private javax.swing.JMenuItem mniproduto;
    private javax.swing.JMenuItem mnisair;
    private javax.swing.JMenu mnpesquisa;
    private javax.swing.JMenu mnrelatorios;
    private javax.swing.JMenuItem pcliente;
    // End of variables declaration//GEN-END:variables
}
